baseURL = "https://yourusername.github.io/"
languageCode = "es"
title = "Laura & Noah"
theme = "PaperMod"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
  ShowReadingTime = false
  disableSearch = true
  disableThemeToggle = true
  defaultTheme = "light"
  hideFooter = true
  robotsNoIndex = true

[[menu.main]]
  identifier = "fecha_y_lugar"
  name = "Fecha y Lugar"
  url = "/fecha_y_lugar/"
  weight = 1

[[menu.main]]
  identifier = "vestimenta"
  name = "Dress Code"
  url = "/vestimenta/"
  weight = 4

[[menu.main]]
  identifier = "alojamiento"
  name = "Alojamiento"
  url = "/alojamiento/"
  weight = 5
